SELECT * FROM SECTION;
SELECT * FROM TEACHES;
SELECT * FROM TAKES;
SELECT * FROM INSTRUCTOR;
SELECT * FROM DEPARTMENT;


SELECT COURSE_ID
FROM SECTION
WHERE SEMESTER = 'Fall' AND YEAR=2009 AND COURSE_ID NOT IN(
        SELECT COURSE_ID
        FROM SECTION
        WHERE SEMESTER = 'Spring' AND YEAR=2010);
        
        
SELECT COUNT(DISTINCT ID)
FROM TAKES
WHERE (COURSE_ID, SEC_ID, SEMESTER, YEAR) IN
        (SELECT COURSE_ID, SEC_ID, SEMESTER, YEAR
        FROM TEACHES
        WHERE ID = 10101);
        
        
SELECT NAME, SALARY
FROM INSTRUCTOR
WHERE SALARY > ALL(SELECT SALARY
                    FROM INSTRUCTOR
                    WHERE DEPT_NAME = 'Comp. Sci.');


SELECT COURSE_ID
FROM SECTION S1
WHERE SEMESTER = 'Fall' AND YEAR=2009 AND NOT EXISTS(
        SELECT *
        FROM SECTION S2
        WHERE SEMESTER = 'Spring' AND YEAR=2010
        AND S1.COURSE_ID = S2.COURSE_ID);
        
SELECT DEPT_NAME, AVG_SAL       
FROM (  SELECT DEPT_NAME, ROUND(AVG(SALARY),2) AS AVG_SAL
        FROM INSTRUCTOR
        GROUP BY DEPT_NAME)
WHERE AVG_SAL>42000;

WITH MAX_BUDGET AS
(SELECT MAX(BUDGET) AS MAX_VALUE
FROM DEPARTMENT)

SELECT DEPT_NAME, BUDGET
FROM DEPARTMENT, MAX_BUDGET
WHERE BUDGET = MAX_VALUE;

SELECT * FROM COURSE;
SELECT * FROM PREREQ;

SELECT *
FROM COURSE NATURAL FULL OUTER JOIN PREREQ;

SELECT *
FROM COURSE LEFT OUTER JOIN PREREQ
ON prereq.course_id = COURSE.COURSE_ID;

INSERT INTO DEPARTMENT VALUES('Robotics','AB3',55000);

SELECT DEPT_NAME, COUNT(ID)
FROM DEPARTMENT NATURAL FULL OUTER JOIN INSTRUCTOR
GROUP BY DEPT_NAME;


