SELECT * FROM depositor;
SELECT * FROM borrower;
SELECT * FROM account;
SELECT * FROM loan;
SELECT * FROM customer;
SELECT * FROM branch;


SELECT CHR(65)
FROM DUAL;

SELECT CHR(65)
FROM DUAL;

SELECT CONCAT('Tech on', ' the Net')
FROM DUAL;

SELECT CONCAT(CONCAT(CUSTOMER_STREET,', '),CUSTOMER_CITY) AS CUSTOMER_ADDRESS
FROM CUSTOMER;

SELECT CUSTOMER_STREET || ', ' || CUSTOMER_CITY  AS CUSTOMER_ADDRESS
FROM CUSTOMER;

SELECT INITCAP('mahmuda rawnak jahan')
from dual;

SELECT INSTR('Tech on the net','net',1) 
FROM DUAL;

SELECT CUSTOMER_NAME, LENGTH(CUSTOMER_NAME) AS NAME_LENGTH
FROM CUSTOMER;

SELECT CUSTOMER_NAME
FROM CUSTOMER
WHERE LENGTH(CUSTOMER_NAME)>=7
AND CUSTOMER_NAME LIKE 'M%';


SELECT CUSTOMER_CITY
FROM CUSTOMER
WHERE lower(CUSTOMER_NAME) = 'williams';

select initcap(customer_name)
from customer;

SELECT RPAD('CSE',11, '103')
FROM DUAL;


SELECT  LTRIM(RTRIM('xyxzyyyTechxyx','xyz'),'xyz')
FROM DUAL;


select ADD_MONTHS('21-Aug-03',3) from dual;

SELECT EXTRACT(DAY FROM DATE '2003-08-22')
from dual;

SELECT SYSDATE
FROM DUAL;
